image: ubuntu-20.04-standard_20.04-1_amd64.tar.gz
ostype: ubuntu
disk_size: 8
cpu_cores: 1
cpu_units: 1024
memory: 512
swap: 512
firewall_file: firewall.j2
redirected_ports: []
allow_ssh: yes
blackbox:
  enable: yes
