
        # Generated by ansible2nix from file requirements.yml
        [
        (builtins.fetchurl {
            name = "devsec.hardening";
            url = "https://galaxy.ansible.com/download/devsec-hardening-9.0.1.tar.gz";
            sha256 = "1drrav0df8rhwx4c3qnv9xgknq7g2a5ik6frg6384q61x53k65rs";
        })
    ]
