image: alpine-3.15-default_20211202_amd64.tar.xz
ostype: alpine
disk_size: 8
cpu_cores: 1
cpu_units: 1024
memory: 256
swap: 256
firewall_file: firewall.j2
redirected_ports: []
allow_ssh: no
blackbox:
  enable: yes
  uri: /js/embed.min.js
