---
- name: Set hostvars
  set_fact:
    host: "{{ hostvars[item] }}"
    main_domain: "{{ item }}"
    ctid: "{{ hostvars[item].lxc_host }}"
    vlan: "{{ hostvars[item].vlan }}"
    passphrase: "{{ hostvars[item].zfs_volume_passphrase }}"
    backup_passphrase: "{{ hostvars[item].backup_passphrase }}"
    role: "{{ hostvars[item].role }}"
    zfs_volume: "{{ hostvars[item].pool }}"
    inventory_index: "{{ groups['containers'].index(item) }}"
    name: "{{ item }}"
    domain: "{{ main_domain }}"
    ct_hostname: "{{ main_domain }}"
    zfs_volume_passphrase: "{{ passphrase }}"
    backup_ssh_key: "{{ hostvars[item].backup_ssh_key }}"
    backup_ssh_pub_key: "{{ hostvars[item].backup_ssh_pub_key }}"
    mail_account_passphrase: "{{ hostvars[item].mail_account_passphrase }}"
    extra_secrets: "{{ hostvars[item].extra_secrets }}"
    pool: "{{ zfs_volume }}"
- name: Include role
  include_role:
    name: "{{ host.role }}"
    tasks_from: container
...
