image: ubuntu-20.04-standard_20.04-1_amd64.tar.gz
ostype: ubuntu
disk_size: 8
cpu_cores: 2
cpu_units: 2048
memory: 4096
swap: 4096
firewall_file: firewall.j2
redirected_ports: []
allow_ssh: yes
blackbox:
  enable: yes
