---
- name: Set custom facts
  set_fact:
    image: "alpine-3.11-default_20200425_amd64.tar.xz"
    ostype: "alpine"
    disk_size: "32"
    cpu_cores: "2"
    cpu_units: "1024"
    memory: "2048"
    swap: "1024"
    firewall_file: "firewall_matrix.j2"
    allow_ssh: "no"
    redirected_ports:
      - value: 3478
        proto: tcp
      - value: 3478
        proto: udp
      - value: 5349
        proto: tcp
      - value: 5349
        proto: udp
- name: Setup container
  include_role:
    name: app
    tasks_from: container
...


