---
- name: Create secrets
  set_fact:
    database_password: "{{ hostvars[item].database_password | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"
    registration_shared_secret: "{{ hostvars[item].registration_shared_secret | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"
    form_secret: "{{ hostvars[item].form_secret | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"
    redis_pass: "{{ hostvars[item].redis_pass | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"


- name: Set extra secrets
  set_fact:
    extra_secrets:
      database_password: "{{ database_password }}"
      registration_shared_secret: "{{ registration_shared_secret }}"
      form_secret: "{{ form_secret }}"
      redis_pass: "{{ redis_pass }}"
...
