---
- name: Setup system
  include_role:
    name: app_ubuntu
    tasks_from: system

- name: Set up web directory
  file:
    path: /srv/public
    owner: www-data
    group: www-data
    mode: 0755

- name: Change www-data home directory
  user:
    name: www-data
    home: /srv
    system: yes

- name: Change www-data home directory
  user:
    name: www-data
    home: /srv

- name: Load vars from Funkwhale role
  include_vars:
    file: extra_roles/funkwhale-ansible/defaults/main.yml

- name: Override vars
  set_fact:
    funkwhale_install_path: "/srv/funkwhale"
    funkwhale_domain: "{{ inventory_hostname }}"
    funkwhale_version: "1.1.1"
    funkwhale_hostname: "{{ inventory_hostname }}"
    funkwhale_nginx_managed: false
    funkwhale_api_ip: "10.0.{{ vlan }}.{{ ctid }}"
    funkwhale_api_port: 8000
    funkwhale_media_path: "/srv/public/media"
    funkwhale_static_path: "/srv/public/static"
    funkwhale_web_workers: 2
    funkwhale_env_vars:
      - "EMAIL_CONFIG=smtp://localhost"

- name: Apply Funkwhale role
  include_role:
    name: extra_roles/funkwhale-ansible

- name: Shamelessly copy the Funkwhale front inside the public share
  copy:
    src: /srv/funkwhale/front
    dest: /srv/public/
    owner: www-data
    group: www-data
    remote_src: yes
...

