---
- name: Set custom facts
  set_fact:
    image: ubuntu-20.04-standard_20.04-1_amd64.tar.gz
    ostype: ubuntu
    disk_size: 32
    cpu_cores: 2
    cpu_units: 1024
    memory: 4096
    swap: 1024
    firewall_file: firewall.j2
    allow_ssh: yes
    redirected_ports:
      - value: 5222
        proto: tcp
      - value: 5269
        proto: tcp
      - value: 1935
        proto: tcp
- name: Setup container
  include_role:
    name: app_ubuntu
    tasks_from: container
...
