---
- name: Set custom facts
  set_fact:
    image: "alpine-3.18-default_20230607_amd64.tar.xz"
    ostype: "alpine"
    disk_size: "8"
    cpu_cores: "2"
    cpu_units: "1024"
    memory: "1024"
    swap: "512"
    firewall_file: "firewall.j2"
    allow_ssh: "no"
    redirected_ports: []
- name: Setup container
  include_role:
    name: app
    tasks_from: container
...

