---
- name: Create admin account password
  set_fact:
    django_admin_password: "{{ hostvars[item].admin_password | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"

- name: Create Django DB password
  set_fact:
    database_password: "{{ hostvars[item].database_password | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"

- name: Create secret key
  set_fact:
    secret_key: "{{ hostvars[item].secret_key | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"

- name: Set extra secrets
  set_fact:
    extra_secrets:
      django_admin_password: "{{ django_admin_password }}"
      database_password: "{{ database_password }}"
      secret_key: "{{ secret_key }}"
...
