image: alpine-3.11-default_20200425_amd64.tar.xz
ostype: alpine
disk_size: 8
cpu_cores: 2
cpu_units: 1024
memory: 2048
swap: 1024
firewall_file: firewall.j2
redirected_ports: []
blackbox:
  enable: yes
