image: ubuntu-22.04-standard_22.04-1_amd64.tar.zst
ostype: ubuntu
disk_size: 128
cpu_cores: 2
cpu_units: 2048
memory: 3072
swap: 2048
firewall_file: firewall.j2
redirected_ports: []
blackbox:
  enable: yes
