image: "alpine-3.15-default_20211202_amd64.tar.xz"
ostype: "alpine"
disk_size: "32"
cpu_cores: "2"
cpu_units: "1024"
memory: "2048"
swap: "1024"
firewall_file: "firewall_matrix.j2"
allow_ssh: "no"
redirected_ports:
  - value: 3478
    proto: tcp
  - value: 3478
    proto: udp
  - value: 5349
    proto: tcp
  - value: 5349
    proto: udp
blackbox:
  enable: yes
