---
- name: Set custom facts
  set_fact:
    image: alpine-3.17-default_20221129_amd64.tar.xz
    ostype: "alpine"
    disk_size: "8"
    cpu_cores: "1"
    cpu_units: "1024"
    memory: "1024"
    swap: "1024"
    firewall_file: "firewall.j2"
    allow_ssh: "yes"
    redirected_ports: []
- name: Setup container
  include_role:
    name: app
    tasks_from: container
...

